import { updateResolvedCount } from './storage.js';

export function renderMessage(role, content, tokens = 0) {
    const div = document.createElement('div');
    div.className = `message ${role}-msg`;

    const time = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    
    if (role === 'user') {
        div.innerHTML = `<div class="msg-header"><span>You</span><span>${time}</span></div><div>${escapeHTML(content)}</div>`;
    } else {
        const htmlContent = parseMarkdown(content);
        div.innerHTML = `
            <div class="msg-header">
                <div><span>AntiGravity</span> <span class="tag-info" style="margin-left:8px;font-size:0.7rem;padding:2px 6px;border-radius:4px;background:rgba(59,130,246,0.2);">Bot</span></div>
                <span>${time}</span>
            </div>
            <div class="msg-body">${htmlContent}</div>
            <div class="bot-actions">
                <button class="action-btn copy-msg" aria-label="Copy message">📋 Copy</button>
                <button class="action-btn btn-helpful" aria-label="Mark helpful">👍 Helpful</button>
                <button class="action-btn btn-unhelpful" aria-label="Mark unhelpful">👎 Not helpful</button>
                ${tokens > 0 ? `<span style="margin-left:auto;font-size:0.75rem;color:var(--text-sub)">${tokens} tokens</span>` : ''}
            </div>
        `;

        setupBotActions(div, content);
        setupCodeBlocks(div);
    }
    return div;
}

export function renderTypingIndicator() {
    const div = document.createElement('div');
    div.id = 'typing-indicator';
    div.className = 'message bot-msg typing-indicator';
    div.style.width = '80px';
    div.style.padding = '12px 20px';
    div.innerHTML = `<span></span><span></span><span></span>`;
    return div;
}

export function removeTypingIndicator() {
    const el = document.getElementById('typing-indicator');
    if (el) el.remove();
}

export function renderErrorMsg(errorMessage, retryCallback, payloadMsg) {
    const div = document.createElement('div');
    div.className = 'error-card message bot-msg';
    div.innerHTML = `
        <span>⚠️ ${escapeHTML(errorMessage)}</span>
        <button class="retry-btn">Retry</button>
    `;
    div.querySelector('.retry-btn').addEventListener('click', () => {
        div.remove();
        document.getElementById('chat-input').value = payloadMsg;
        retryCallback();
    });
    return div;
}

function parseMarkdown(text) {
    if (!text) return '';
    const parts = text.split(/(```[\s\S]*?```)/g);
    let html = '';
    
    parts.forEach(part => {
        if (part.startsWith('```') && part.endsWith('```')) {
            const match = part.match(/```([a-zA-Z0-9+\-#_]*)\n([\s\S]*?)```/);
            if (match) {
                const lang = match[1] || 'text';
                const code = escapeHTML(match[2].trim());
                html += `
                <div class="code-block">
                    <div class="code-header">
                        <span class="code-lang">${lang}</span>
                        <button class="copy-btn">Copy</button>
                    </div>
                    <pre><code class="language-${lang}">${code}</code></pre>
                </div>`;
            }
        } else {
            let processed = escapeHTML(part);
            processed = processed.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
            processed = processed.replace(/`([^`\n]+)`/g, '<code class="inline-code">$1</code>');
            // Basic list rendering mapping
            processed = processed.replace(/^\s*[-*]\s+(.*)$/gm, '<li>$1</li>');
            processed = processed.replace(/(<li>.*<\/li>)/gs, '<ul>$1</ul>');
            processed = processed.replace(/\n\n/g, '<br><br>');
            html += processed;
        }
    });
    
    // Clean up nested ULs generated by simple regex
    html = html.replace(/<\/ul>\s*<ul>/g, '');
    return html;
}

function escapeHTML(str) {
    return str.replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
}

function setupBotActions(container, rawContent) {
    const copyBtn = container.querySelector('.copy-msg');
    copyBtn.addEventListener('click', async () => {
        await navigator.clipboard.writeText(rawContent);
        copyBtn.innerHTML = '✅ Copied!';
        setTimeout(() => copyBtn.innerHTML = '📋 Copy', 2000);
    });

    const helpfulBtn = container.querySelector('.btn-helpful');
    const unhelpfulBtn = container.querySelector('.btn-unhelpful');

    helpfulBtn.addEventListener('click', () => {
        helpfulBtn.innerHTML = '✅ Helpful';
        helpfulBtn.style.color = 'var(--tag-success)';
        unhelpfulBtn.style.display = 'none';
        helpfulBtn.disabled = true;
        updateResolvedCount();
        document.getElementById('stat-resolved').textContent = JSON.parse(localStorage.getItem('ag_stats')).resolved;
    });

    unhelpfulBtn.addEventListener('click', () => {
        unhelpfulBtn.innerHTML = '❌ Not helpful';
        unhelpfulBtn.style.color = 'var(--tag-danger)';
        helpfulBtn.style.display = 'none';
        unhelpfulBtn.disabled = true;
    });
}

function setupCodeBlocks(container) {
    container.querySelectorAll('.code-block').forEach(block => {
        const btn = block.querySelector('.copy-btn');
        const code = block.querySelector('code').innerText;
        btn.addEventListener('click', async () => {
            await navigator.clipboard.writeText(code);
            btn.textContent = 'Copied!';
            setTimeout(() => btn.textContent = 'Copy', 2000);
        });
    });
}
